---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql

  post_tasks:
    - name: Make sure the PHP MySQL extension is present.
      command: "php -i | grep 'mysqlnd => enabled'"
      changed_when: false
